[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:39201/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:42433/], count 1
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:37163/], count 2
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:33805/], count 3
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:43759/], count 3
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:36045/], count 3
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:36541/], count 3
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:34849/], count 3
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:42111/], count 5
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:46883/], count 5
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf_static] adding connection to [http://192.168.0.101:37137/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:37137/], count 10
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:38545/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:38545/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:38545/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/goal] adding connection to [/hsrb/impedance_control], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/cancel] adding connection to [/hsrb/impedance_control], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/joint_states] adding connection to [http://192.168.0.101:42111/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/feedback] adding connection to [http://192.168.0.101:43049/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/result] adding connection to [http://192.168.0.101:43049/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/status] adding connection to [http://192.168.0.101:43049/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/goal] adding connection to [/mdr_actions/perceive_plane_server], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/cancel] adding connection to [/mdr_actions/perceive_plane_server], count 0
[32mINFO    [0m rospy.core:core.py:454 signal_shutdown [signal-2]
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/goal] removing connection to /hsrb/impedance_control
[32mINFO    [0m rospy.internal:core.py:138 topic[/rosout] removing connection to /rosout
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/cancel] removing connection to /mdr_actions/perceive_plane_server
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/cancel] removing connection to /hsrb/impedance_control
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/goal] removing connection to /mdr_actions/perceive_plane_server
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:42111/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:39201/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:42433/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:37163/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:33805/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:43759/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:55163 (http://192.168.0.101:43759/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:56953 (http://192.168.0.101:33805/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[1m[31mERROR   [0m rospy.topics:topics.py:329 Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 839, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:36045/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:36541/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[1m[31mERROR   [0m rospy.topics:topics.py:329 Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 839, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:33795 (http://192.168.0.101:36045/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:56149 (http://192.168.0.101:36541/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:34849/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:46883/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:37137/
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/result] removing connection to http://192.168.0.101:43049/
[32mINFO    [0m rospy.internal:core.py:138 topic[/clock] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf_static] removing connection to http://192.168.0.101:37137/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/status] removing connection to http://192.168.0.101:38545/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:39417 (http://192.168.0.101:37137/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:38545/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/gripper_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/joint_states] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/head_trajectory_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/status] removing connection to http://192.168.0.101:43049/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/arm_trajectory_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:42111/
[32mINFO    [0m rospy.internal:core.py:138 topic[/mdr_actions/perceive_plane_server/feedback] removing connection to http://192.168.0.101:43049/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:41565 (http://192.168.0.101:43049/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/impedance_control/follow_joint_trajectory/result] removing connection to http://192.168.0.101:38545/
[32mINFO    [0m rospy.impl.masterslave:masterslave.py:342 signal-2
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:49319 (http://192.168.0.101:42111/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:37065 (http://192.168.0.101:38545/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:43725 (http://192.168.0.101:34849/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 636, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 422, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[32mINFO    [0m rospy.core:core.py:454 signal_shutdown [shutdown]