{"status": "broken", "description": "Activating the pick action test and checking whether it was successful.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "complex_test"}, {"name": "subSuite", "value": "TestComplexScenario"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "16109-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.complex_test"}], "stop": 1608371119826, "uuid": "7722c3d5-0f59-4d59-9a7b-fe3ebab82547", "historyId": "6df5cbf7c00ce5f14b4c42d69bcd2de9", "name": "test_verification_of_pick_action", "start": 1608371117531, "fullName": "tests.complex_test.TestComplexScenario#test_verification_of_pick_action", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <tests.complex_test.TestComplexScenario instance at 0x7f54ee91bc68>\n\n    def test_verification_of_pick_action(self):\n        \"\"\"Activating the pick action test and checking whether it was successful.\n        \"\"\"\n        data_logger('logger/logs/pick_action_start')\n        # Pick from table and place on table\n        result = MoveItPickAndPlace(pick_x = -0.03, pick_y = 0.96 , pick_z = 0.57,\n>                                   place_x = 0.5, place_y = 1.0 , place_z = 0.6)\n\ntests/complex_test.py:173: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npick_x = -0.03, pick_y = 0.96, pick_z = 0.57, place_x = 0.5, place_y = 1.0\nplace_z = 0.6\n\n    def MoveItPickAndPlace(pick_x = 0, pick_y = 0, pick_z = 0, place_x = 0, place_y = 0, place_z = 0):\n        # Prepare hsrb_interface\n        robot = hsrb_interface.Robot()\n        whole_body = robot.get(\"whole_body\")\n        omni_base = robot.get(\"omni_base\")\n        gripper = robot.get(\"gripper\")\n    \n        # collision_world.add_box(x=3, y=1.375, z=0.46, pose=geometry.pose(x=0,y=2, z= 0.25), frame_id='map')\n>       whole_body.collision_world = hsrb_interface.collision_world()\nE       TypeError: 'module' object is not callable\n\ntests/action_client/experimental_pick_place_client.py:29: TypeError"}, "attachments": [{"source": "b54d7905-b917-42cf-bd93-3571fde1d27c-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "08999b18-16f2-4dd0-88d1-07bf38ffdb2a-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "8a8d28f4-e1b4-49db-b4e9-7aa1f314456a-attachment.txt", "type": "text/plain", "name": "stderr"}]}