{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "31178-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608395074391, "uuid": "20a27d61-e7d0-424a-b71b-ce15d4e0e8c1", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608395074261, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7fe8fddb2098>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:79: NameError"}, "attachments": [{"source": "deb5a73c-31b5-4cfa-a62f-3ea6cc0d67f4-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "3f3ea1bf-521f-4bd6-81de-9a0d35306ee6-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "a447a32f-9abc-45a6-a3a4-59fd835f1c17-attachment.txt", "type": "text/plain", "name": "stderr"}]}