{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "31425-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608395160074, "uuid": "2b239d48-ffef-4f66-b127-323f6be021ce", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608395159902, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7f0989f8d6c8>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:79: NameError"}, "attachments": [{"source": "989053a8-76f3-4643-94b3-f81e10e5761c-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "262546c4-0b69-4b63-ad5f-eed6b782aefb-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "020d8dd8-f3be-4be6-9b92-65d3ac40fb02-attachment.txt", "type": "text/plain", "name": "stderr"}]}