{"status": "broken", "description": "Activating the pick action test and checking whether it was successful.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "complex_test"}, {"name": "subSuite", "value": "TestComplexScenario"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "26283-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.complex_test"}], "stop": 1608382017950, "uuid": "23dac033-b1b9-4b2e-9b88-e1ebfb5c524a", "historyId": "6df5cbf7c00ce5f14b4c42d69bcd2de9", "name": "test_verification_of_pick_action", "start": 1608382015596, "fullName": "tests.complex_test.TestComplexScenario#test_verification_of_pick_action", "statusDetails": {"message": "NameError: global name 'collision_world' is not defined", "trace": "self = <tests.complex_test.TestComplexScenario instance at 0x7f30e49836c8>\n\n    def test_verification_of_pick_action(self):\n        \"\"\"Activating the pick action test and checking whether it was successful.\n        \"\"\"\n        data_logger('logger/logs/pick_action_start')\n        attempt = 0\n        while attempt<15:\n            try:\n                result = MoveItPickAndPlace(pick_x = -0.03, pick_y = 0.96 , pick_z = 0.56,\n>                                           place_x = 0.5, place_y = 1.0 , place_z = 0.65)\n\ntests/complex_test.py:174: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npick_x = -0.03, pick_y = 0.96, pick_z = 0.56, place_x = 0.5, place_y = 1.0\nplace_z = 0.65\n\n    def MoveItPickAndPlace(pick_x = 0, pick_y = 0, pick_z = 0, place_x = 0, place_y = 0, place_z = 0):\n        # Prepare hsrb_interface\n        robot = hsrb_interface.Robot()\n        whole_body = robot.get(\"whole_body\")\n        omni_base = robot.get(\"omni_base\")\n        gripper = robot.get(\"gripper\")\n>       whole_body.collision_world  = collision_world\nE       NameError: global name 'collision_world' is not defined\n\ntests/action_client/experimental_pick_place_client.py:26: NameError"}, "attachments": [{"source": "37973593-0498-4329-b707-f0f815fa32df-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "6e9a0f6c-3f14-4c34-81c2-72caaca3c5e1-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "88eb68c3-966f-4723-ba8d-cb4494497467-attachment.txt", "type": "text/plain", "name": "stderr"}]}