{"name": "test_set_up", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'utilities/config.txt'", "trace": "self = <nav_test.TestNavigation object at 0x7f814eab3ac0>\n\n    @pytest.fixture(autouse=True)\n    def set_up(self):\n>       self.config = Configuration()\n\nnav_test.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <property_based_tester.tests.file_reader.file_reader.Configuration object at 0x7f814eab3b50>\n\n    def __init__(self):\n    \n        self.rospakg       = 'atg'\n        self.ros_file_name = 'hsr.launch'\n    \n>       with open(\"utilities/config.txt\",mode='r') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'utilities/config.txt'\n\nfile_reader/file_reader.py:28: FileNotFoundError"}, "description": "Initializing navigation scenario.\n        ", "start": 1656500852570, "stop": 1656500852570, "uuid": "ec232a49-44f0-4fa3-b7b9-2f5b35fe8dca", "historyId": "be8ca0dc772e86020154f3294ac9ad1a", "testCaseId": "1809364b5ba5aa5c893a2c2b31286f64", "fullName": "src.property_based_tester.tests.nav_test.TestNavigation#test_set_up", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('set_up')"}, {"name": "parentSuite", "value": "src.property_based_tester.tests"}, {"name": "suite", "value": "nav_test"}, {"name": "subSuite", "value": "TestNavigation"}, {"name": "host", "value": "legion"}, {"name": "thread", "value": "36868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.property_based_tester.tests.nav_test"}]}