{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "17233-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608394352229, "uuid": "8375cac8-208c-476b-a47d-2c0d6e7863db", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608394352084, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7f30c7c80098>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:77: NameError"}, "attachments": [{"source": "9bac5a1d-2685-484d-addc-b9b6cd73e780-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "60431df6-cce7-44a4-9a95-469b63654f91-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "ff2d6f5a-186f-4fae-97e4-e40ce3f329c1-attachment.txt", "type": "text/plain", "name": "stderr"}]}