{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "31038-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608395036800, "uuid": "0767bca8-da01-4132-aef3-c1de37ec7882", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608395036701, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7fd1b14a0fc8>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:79: NameError"}, "attachments": [{"source": "3a8154df-ee4f-481a-84a3-9e827b9f4dee-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "3ef1f112-d858-431e-9b46-174dbffca5c7-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "ed71e685-8a04-438b-a04b-c99df208fb68-attachment.txt", "type": "text/plain", "name": "stderr"}]}