{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "17365-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608394383874, "uuid": "05dae557-0031-45ec-a924-1c244a7f1d5f", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608394383707, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7f1e69c81f80>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:78: NameError"}, "attachments": [{"source": "8442bb2a-5a32-4c93-93ca-adf82f0e15f0-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "27b37f5d-77d3-4f05-b8ff-05a28d386e0c-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "f02fc599-078b-4ebf-89b1-9750c5173711-attachment.txt", "type": "text/plain", "name": "stderr"}]}