{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "17597-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608394429535, "uuid": "d12d80e2-798e-4b5a-9594-c5cb968bcb66", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608394429396, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7f68b50b5ef0>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:78: NameError"}, "attachments": [{"source": "a4698fb3-b470-4477-a578-6814ab4cb7f1-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "2c2213ef-b6f5-4330-a252-d2fad34dda66-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "0e261542-01c4-4cca-bdfc-81f7f766c13f-attachment.txt", "type": "text/plain", "name": "stderr"}]}