{"name": "test_verification_of_navigation", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'utilities/config.txt'", "trace": "self = <nav_test.TestNavigation object at 0x7f814ea31790>\n\n    @pytest.fixture(autouse=True)\n    def set_up(self):\n>       self.config = Configuration()\n\nnav_test.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <property_based_tester.tests.file_reader.file_reader.Configuration object at 0x7f814ea31a30>\n\n    def __init__(self):\n    \n        self.rospakg       = 'atg'\n        self.ros_file_name = 'hsr.launch'\n    \n>       with open(\"utilities/config.txt\",mode='r') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'utilities/config.txt'\n\nfile_reader/file_reader.py:28: FileNotFoundError"}, "description": "Defines a scenario for the rest of the tests to run in using coodrinates.\n        ", "start": 1656500852605, "stop": 1656500852605, "uuid": "1d8d7bd7-f9d7-45be-8d3c-175575d43eff", "historyId": "ba6902015cb9450d2de8d172ac76cf0f", "testCaseId": "807c1e7d37a89f96ae430cc1a14af8cf", "fullName": "src.property_based_tester.tests.nav_test.TestNavigation#test_verification_of_navigation", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('set_up')"}, {"name": "parentSuite", "value": "src.property_based_tester.tests"}, {"name": "suite", "value": "nav_test"}, {"name": "subSuite", "value": "TestNavigation"}, {"name": "host", "value": "legion"}, {"name": "thread", "value": "36868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.property_based_tester.tests.nav_test"}]}