{"status": "broken", "description": "Activating the pick action test and checking whether it was successful.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "complex_test"}, {"name": "subSuite", "value": "TestComplexScenario"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "15636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.complex_test"}], "stop": 1608296188445, "uuid": "9c042d87-6c61-49ef-87b0-547dcf3ffc3a", "historyId": "6df5cbf7c00ce5f14b4c42d69bcd2de9", "name": "test_verification_of_pick_action", "start": 1608296186537, "fullName": "tests.complex_test.TestComplexScenario#test_verification_of_pick_action", "statusDetails": {"message": "UnboundLocalError: local variable 'points_data' referenced before assignment", "trace": "self = <tests.complex_test.TestComplexScenario instance at 0x7fc8b0bbd8c0>\n\n    def test_verification_of_pick_action(self):\n        \"\"\"Activating the pick action test and checking whether it was successful.\n        \"\"\"\n        rgbd = RGBD()\n        move_head_tilt(-0.5)\n>       while points_data != None:\nE       UnboundLocalError: local variable 'points_data' referenced before assignment\n\ntests/complex_test.py:172: UnboundLocalError"}, "attachments": [{"source": "22239f55-5b27-496d-bafd-67f962411a7d-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "6a158f00-b49a-4cb3-9708-ebbb6d4caa31-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "364b8ca8-84aa-4646-92eb-94d1b25817ba-attachment.txt", "type": "text/plain", "name": "stderr"}]}