{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "30888-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608394974220, "uuid": "667c6a56-a409-4252-bb2d-d54d5d3dbdd8", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608394974103, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7f746fbc9fc8>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:79: NameError"}, "attachments": [{"source": "3c93fede-7cae-4c25-ac8c-ab065bf7b676-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "f8c28f37-9ae9-4dc8-bd99-080abd992c83-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "ec73822e-767d-4143-a87d-d087096b45f1-attachment.txt", "type": "text/plain", "name": "stderr"}]}