{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "16948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608394277875, "uuid": "e775b6a9-11a7-4317-b9fe-c1c1a123f6bc", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608394277663, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7f6643eb5a70>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:77: NameError"}, "attachments": [{"source": "cdb75876-e3c0-480f-8016-da733cc1b29c-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "0089b8d0-541f-40b4-a09a-9754e504fb53-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "35d4645a-8532-4f23-b27f-e4b2111267f0-attachment.txt", "type": "text/plain", "name": "stderr"}]}