{"status": "broken", "description": "Activating the pick action test and checking whether it was successful.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "complex_test"}, {"name": "subSuite", "value": "TestComplexScenario"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "13014-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.complex_test"}], "stop": 1608339736509, "uuid": "3077a28f-80cd-4ecd-b026-44e5b9798216", "historyId": "6df5cbf7c00ce5f14b4c42d69bcd2de9", "name": "test_verification_of_pick_action", "start": 1608339734012, "fullName": "tests.complex_test.TestComplexScenario#test_verification_of_pick_action", "statusDetails": {"message": "NameError: global name 'CollisionWorld' is not defined", "trace": "self = <tests.complex_test.TestComplexScenario instance at 0x7fd82f04b3b0>\n\n    def test_verification_of_pick_action(self):\n        \"\"\"Activating the pick action test and checking whether it was successful.\n        \"\"\"\n        data_logger('logger/logs/pick_action_start')\n        # Pick from table and place on table\n        result = MoveItPickAndPlace(pick_x = -0.03, pick_y = 0.96 , pick_z = 0.57,\n>                                   place_x = 0.5, place_y = 1.0 , place_z = 0.6)\n\ntests/complex_test.py:173: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npick_x = -0.03, pick_y = 0.96, pick_z = 0.57, place_x = 0.5, place_y = 1.0\nplace_z = 0.6\n\n    def MoveItPickAndPlace(pick_x = 0, pick_y = 0, pick_z = 0, place_x = 0, place_y = 0, place_z = 0):\n        # Prepare hsrb_interface\n        robot = hsrb_interface.Robot()\n        whole_body = robot.get(\"whole_body\")\n        omni_base = robot.get(\"omni_base\")\n    \n        gripper = robot.get(\"gripper\")\n    \n>       collision_world = CollisionWorld\nE       NameError: global name 'CollisionWorld' is not defined\n\ntests/action_client/experimental_pick_place_client.py:28: NameError"}, "attachments": [{"source": "39b77bc3-12cd-4d7b-9396-4e943075b0dc-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "14815e38-a676-445a-a794-6f41f666880e-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "90e47070-8344-40a1-a4a8-4bcacd5a8670-attachment.txt", "type": "text/plain", "name": "stderr"}]}