{"status": "broken", "description": "Activates perception action.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "perceive_test"}, {"name": "subSuite", "value": "TestPerception"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "30595-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.perceive_test"}], "stop": 1608394799318, "uuid": "12c4f07b-9d8a-472a-98f1-fc5fefb6f02d", "historyId": "5d9539f0f5eac3b37dd676d398f61a55", "name": "test_verification_of_perception", "start": 1608394799161, "fullName": "tests.perceive_test.TestPerception#test_verification_of_perception", "statusDetails": {"message": "NameError: global name 'result' is not defined", "trace": "self = <tests.perceive_test.TestPerception instance at 0x7fada4802ea8>\n\n    def test_verification_of_perception(self):\n        \"\"\"Activates perception action.\n        \"\"\"\n        data_logger('logger/logs/perception')\n        # result = perceive_client()\n>       assert True == result\nE       NameError: global name 'result' is not defined\n\ntests/perceive_test.py:79: NameError"}, "attachments": [{"source": "7c962947-397e-40f5-8bf6-7da059aca4e4-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "6594afc0-ecaa-42c2-a4b3-3a6657f5db81-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "0432cea0-2552-42d0-a47c-8e527ba0bdc2-attachment.txt", "type": "text/plain", "name": "stderr"}]}